//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elink.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elink.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bad_cry {
            get {
                object obj = ResourceManager.GetObject("bad_cry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caratula_800x600_1 {
            get {
                object obj = ResourceManager.GetObject("Caratula_800x600_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caratula_800x600_2 {
            get {
                object obj = ResourceManager.GetObject("Caratula_800x600_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chalk {
            get {
                object obj = ResourceManager.GetObject("chalk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon elink {
            get {
                object obj = ResourceManager.GetObject("elink", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap good_smile {
            get {
                object obj = ResourceManager.GetObject("good_smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap just_soso {
            get {
                object obj = ResourceManager.GetObject("just_soso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_big {
            get {
                object obj = ResourceManager.GetObject("logo_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_big_blue {
            get {
                object obj = ResourceManager.GetObject("logo_big_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_small {
            get {
                object obj = ResourceManager.GetObject("logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 NA 的本地化字符串。
        /// </summary>
        internal static string s1000_3082 {
            get {
                return ResourceManager.GetString("s1000_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Está seguro de que quiere cerrar el programa? 的本地化字符串。
        /// </summary>
        internal static string s1001_3082 {
            get {
                return ResourceManager.GetString("s1001_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmar 的本地化字符串。
        /// </summary>
        internal static string s1002_3082 {
            get {
                return ResourceManager.GetString("s1002_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 día 的本地化字符串。
        /// </summary>
        internal static string s1003_3082 {
            get {
                return ResourceManager.GetString("s1003_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 semana 的本地化字符串。
        /// </summary>
        internal static string s1004_3082 {
            get {
                return ResourceManager.GetString("s1004_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mes 的本地化字符串。
        /// </summary>
        internal static string s1005_3082 {
            get {
                return ResourceManager.GetString("s1005_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  por  的本地化字符串。
        /// </summary>
        internal static string s1006_3082 {
            get {
                return ResourceManager.GetString("s1006_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coste medio de la electricidad: {0}{1}/kWh 的本地化字符串。
        /// </summary>
        internal static string s1007_3082 {
            get {
                return ResourceManager.GetString("s1007_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ratio de carbono: {0} kg.CO2/kWh 的本地化字符串。
        /// </summary>
        internal static string s1008_3082 {
            get {
                return ResourceManager.GetString("s1008_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Haga click aquí para acceder a la guía del usuario 的本地化字符串。
        /// </summary>
        internal static string s1009_3082 {
            get {
                return ResourceManager.GetString("s1009_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Los datos han sido recogidos correctamente 的本地化字符串。
        /// </summary>
        internal static string s1010_3082 {
            get {
                return ResourceManager.GetString("s1010_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error en el puerto USB,el monitor no ha podido conectarse correctamente con su PC/MAC 的本地化字符串。
        /// </summary>
        internal static string s1011_3082 {
            get {
                return ResourceManager.GetString("s1011_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Los datos han sido recogidos correctamente 的本地化字符串。
        /// </summary>
        internal static string s1012_3082 {
            get {
                return ResourceManager.GetString("s1012_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 El registro está vacío. No hay datos para copiar. 的本地化字符串。
        /// </summary>
        internal static string s1013_3082 {
            get {
                return ResourceManager.GetString("s1013_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seleccione la carpeta destino: 的本地化字符串。
        /// </summary>
        internal static string s1014_3082 {
            get {
                return ResourceManager.GetString("s1014_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copia de seguridad realizada correctamente. Han sido copiados {0} ficheros 的本地化字符串。
        /// </summary>
        internal static string s1015_3082 {
            get {
                return ResourceManager.GetString("s1015_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Los ficheros no han podido copiarse, ¿está usted seguro de que la carpeta no está protegida? 的本地化字符串。
        /// </summary>
        internal static string s1016_3082 {
            get {
                return ResourceManager.GetString("s1016_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seleccione la carpeta donde se encuentran los ficheros a restaurar 的本地化字符串。
        /// </summary>
        internal static string s1017_3082 {
            get {
                return ResourceManager.GetString("s1017_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 La carpeta origen no existe 的本地化字符串。
        /// </summary>
        internal static string s1018_3082 {
            get {
                return ResourceManager.GetString("s1018_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ha restaurado los ficheros correctamente. Han sido copiados {0} ficheros 的本地化字符串。
        /// </summary>
        internal static string s1019_3082 {
            get {
                return ResourceManager.GetString("s1019_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Los ficheros no han podido restaurarse ¿está usted seguro de que la carpeta de origen no está vacía? 的本地化字符串。
        /// </summary>
        internal static string s1020_3082 {
            get {
                return ResourceManager.GetString("s1020_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Es la primera vez que que utiliza este programa 的本地化字符串。
        /// </summary>
        internal static string s1021_3082 {
            get {
                return ResourceManager.GetString("s1021_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lo primero que debe hacer para el correcto funcionamiento del programa es ajustar su tarifa. Identifíquela con un nombre y ajuste el precio de la electricidad. 的本地化字符串。
        /// </summary>
        internal static string s1022_3082 {
            get {
                return ResourceManager.GetString("s1022_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presione OK para seguir. 的本地化字符串。
        /// </summary>
        internal static string s1023_3082 {
            get {
                return ResourceManager.GetString("s1023_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¡Bienvenido! 的本地化字符串。
        /// </summary>
        internal static string s1024_3082 {
            get {
                return ResourceManager.GetString("s1024_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¡Atención! 的本地化字符串。
        /// </summary>
        internal static string s2000_3082 {
            get {
                return ResourceManager.GetString("s2000_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plan de consumo: {1:0.00}¤/dia. Resultado actual: {0:0.00}¤/dia 的本地化字符串。
        /// </summary>
        internal static string s3000_3082 {
            get {
                return ResourceManager.GetString("s3000_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % más barato 的本地化字符串。
        /// </summary>
        internal static string s3001_3082 {
            get {
                return ResourceManager.GetString("s3001_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % más caro 的本地化字符串。
        /// </summary>
        internal static string s3002_3082 {
            get {
                return ResourceManager.GetString("s3002_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Similar 的本地化字符串。
        /// </summary>
        internal static string s3003_3082 {
            get {
                return ResourceManager.GetString("s3003_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mejor 的本地化字符串。
        /// </summary>
        internal static string s3004_3082 {
            get {
                return ResourceManager.GetString("s3004_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peor 的本地化字符串。
        /// </summary>
        internal static string s3005_3082 {
            get {
                return ResourceManager.GetString("s3005_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inserte el identificador de tarifa e inténtelo de nuevo 的本地化字符串。
        /// </summary>
        internal static string s5002_3082 {
            get {
                return ResourceManager.GetString("s5002_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Está seguro que quiere descartar los cambios y actualizar los  últimos datos guardados? 的本地化字符串。
        /// </summary>
        internal static string s5004_3082 {
            get {
                return ResourceManager.GetString("s5004_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ajustes actualizados 的本地化字符串。
        /// </summary>
        internal static string s5005_3082 {
            get {
                return ResourceManager.GetString("s5005_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Está seguo de guardar los cambios? 的本地化字符串。
        /// </summary>
        internal static string s5006_3082 {
            get {
                return ResourceManager.GetString("s5006_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cambio de ajustes guardados 的本地化字符串。
        /// </summary>
        internal static string s5007_3082 {
            get {
                return ResourceManager.GetString("s5007_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Quiere cambiar de nombre de tarifa o cambiar de perfil tarifario? 的本地化字符串。
        /// </summary>
        internal static string s5008_3082 {
            get {
                return ResourceManager.GetString("s5008_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presione SI para cambiar de nombre. Presione NO para cambiar a un nuevo perfil tarifario 的本地化字符串。
        /// </summary>
        internal static string s5009_3082 {
            get {
                return ResourceManager.GetString("s5009_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presione CANCELAR para volver sin guardar los cambios 的本地化字符串。
        /// </summary>
        internal static string s5010_3082 {
            get {
                return ResourceManager.GetString("s5010_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Está seguro de que quiere actualizar a los valores pord efecto? 的本地化字符串。
        /// </summary>
        internal static string s6000_3082 {
            get {
                return ResourceManager.GetString("s6000_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Seguro que quiere actualizar la tarifa existente? 的本地化字符串。
        /// </summary>
        internal static string s7000_3082 {
            get {
                return ResourceManager.GetString("s7000_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Seguro que quiere eliminar la tarifa seleccionada? 的本地化字符串。
        /// </summary>
        internal static string s7001_3082 {
            get {
                return ResourceManager.GetString("s7001_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ¿Eliminar tarifa? 的本地化字符串。
        /// </summary>
        internal static string s7002_3082 {
            get {
                return ResourceManager.GetString("s7002_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tarifa/s eliminada/s 的本地化字符串。
        /// </summary>
        internal static string s7004_3082 {
            get {
                return ResourceManager.GetString("s7004_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marque tanto el periodo de registro así como la tarifa con la que quiere llevar a cabo la simulación e inténtelo de nuevo 的本地化字符串。
        /// </summary>
        internal static string s7005_3082 {
            get {
                return ResourceManager.GetString("s7005_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 La tarifa ha sido guardada 的本地化字符串。
        /// </summary>
        internal static string s7006_3082 {
            get {
                return ResourceManager.GetString("s7006_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID Tarifa. (*.xml)|*.xml|Todos los ficheros (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string s7007_3082 {
            get {
                return ResourceManager.GetString("s7007_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identifique la tarifa 的本地化字符串。
        /// </summary>
        internal static string s7008_3082 {
            get {
                return ResourceManager.GetString("s7008_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tarifa guardada correctamente 的本地化字符串。
        /// </summary>
        internal static string s7009_3082 {
            get {
                return ResourceManager.GetString("s7009_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 La tarifa {0} pertenece a un registro de consumo y no puede ser eliminado 的本地化字符串。
        /// </summary>
        internal static string s8010_3082 {
            get {
                return ResourceManager.GetString("s8010_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumo 的本地化字符串。
        /// </summary>
        internal static string s9001_3082 {
            get {
                return ResourceManager.GetString("s9001_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 identifica tu tarifa en esta casilla. Por ejemplo: Tarifa 2.03.  的本地化字符串。
        /// </summary>
        internal static string s9002_3082 {
            get {
                return ResourceManager.GetString("s9002_3082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guía de ajustes: 的本地化字符串。
        /// </summary>
        internal static string s9003_3082 {
            get {
                return ResourceManager.GetString("s9003_3082", resourceCulture);
            }
        }
    }
}
